// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  xp: __t.i32(),
  knowsSpark: __t.bool().name("knows_spark"),
  knowsEmberbolt: __t.bool().name("knows_emberbolt"),
  staffEquipped: __t.bool().name("staff_equipped"),
  robesEquipped: __t.bool().name("robes_equipped"),
  hasEmberShard: __t.bool().name("has_ember_shard"),
});
