// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  xp: __t.i32(),
  knowsSpark: __t.bool().name("knows_spark"),
  knowsEmberbolt: __t.bool().name("knows_emberbolt"),
  staffEquipped: __t.bool().name("staff_equipped"),
  robesEquipped: __t.bool().name("robes_equipped"),
  hasEmberShard: __t.bool().name("has_ember_shard"),
  hasYardTonic: __t.bool().name("has_yard_tonic"),
  tonicExpiresAt: __t.timestamp().name("tonic_expires_at"),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  level: __t.i32(),
  lastDamagedAt: __t.timestamp().name("last_damaged_at"),
  restReadyAt: __t.timestamp().name("rest_ready_at"),
  mana: __t.i32(),
  maxMana: __t.i32().name("max_mana"),
  lastManaTickAt: __t.timestamp().name("last_mana_tick_at"),
});
