// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  kind: __t.i32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  spawnX: __t.f32().name("spawn_x"),
  spawnY: __t.f32().name("spawn_y"),
  spawnZ: __t.f32().name("spawn_z"),
  aggroed: __t.bool(),
});
