// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  targetNpcId: __t.u64().name("target_npc_id"),
  gcdReadyAt: __t.timestamp().name("gcd_ready_at"),
  castingSpellId: __t.i32().name("casting_spell_id"),
  castEndsAt: __t.timestamp().name("cast_ends_at"),
  lastSpellId: __t.i32().name("last_spell_id"),
  lastCastAt: __t.timestamp().name("last_cast_at"),
  castPushbackCount: __t.i32().name("cast_pushback_count"),
  castLockedUntil: __t.timestamp().name("cast_locked_until"),
});
