// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Character = __t.object("Character", {
  identity: __t.identity(),
  xp: __t.i32(),
  knowsSpark: __t.bool(),
  knowsEmberbolt: __t.bool(),
  staffEquipped: __t.bool(),
  robesEquipped: __t.bool(),
  hasEmberShard: __t.bool(),
  hasYardTonic: __t.bool(),
  tonicExpiresAt: __t.timestamp(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  level: __t.i32(),
  lastDamagedAt: __t.timestamp(),
  restReadyAt: __t.timestamp(),
  mana: __t.i32(),
  maxMana: __t.i32(),
  lastManaTickAt: __t.timestamp(),
});
export type Character = __Infer<typeof Character>;

export const ChatMessage = __t.object("ChatMessage", {
  messageId: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const CrowdProxy = __t.object("CrowdProxy", {
  proxyId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  far: __t.bool(),
});
export type CrowdProxy = __Infer<typeof CrowdProxy>;

export const Npc = __t.object("Npc", {
  npcId: __t.u64(),
  kind: __t.i32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32(),
});
export type Npc = __Infer<typeof Npc>;

export const PartyChatMessage = __t.object("PartyChatMessage", {
  messageId: __t.u64(),
  partyId: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type PartyChatMessage = __Infer<typeof PartyChatMessage>;

export const PartyInvite = __t.object("PartyInvite", {
  invitee: __t.identity(),
  partyId: __t.u64(),
  inviter: __t.identity(),
});
export type PartyInvite = __Infer<typeof PartyInvite>;

export const PartyMember = __t.object("PartyMember", {
  identity: __t.identity(),
  partyId: __t.u64(),
  isLeader: __t.bool(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const PendingCast = __t.object("PendingCast", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  caster: __t.identity(),
  spellId: __t.i32(),
  targetNpcId: __t.u64(),
});
export type PendingCast = __Infer<typeof PendingCast>;

export const PendingPlayerRespawn = __t.object("PendingPlayerRespawn", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  player: __t.identity(),
});
export type PendingPlayerRespawn = __Infer<typeof PendingPlayerRespawn>;

export const PlayerCombat = __t.object("PlayerCombat", {
  identity: __t.identity(),
  targetNpcId: __t.u64(),
  gcdReadyAt: __t.timestamp(),
  castingSpellId: __t.i32(),
  castEndsAt: __t.timestamp(),
  lastSpellId: __t.i32(),
  lastCastAt: __t.timestamp(),
  castPushbackCount: __t.i32(),
  castLockedUntil: __t.timestamp(),
  stunnedUntilMicros: __t.i64(),
});
export type PlayerCombat = __Infer<typeof PlayerCombat>;

export const PlayerPose = __t.object("PlayerPose", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  interestChunkX: __t.i32(),
  interestChunkZ: __t.i32(),
});
export type PlayerPose = __Infer<typeof PlayerPose>;

export const TradeOffer = __t.object("TradeOffer", {
  to: __t.identity(),
  from: __t.identity(),
  offeredHasEmberShard: __t.bool(),
  offeredXp: __t.i32(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

export const WhisperMessage = __t.object("WhisperMessage", {
  messageId: __t.u64(),
  sender: __t.identity(),
  recipient: __t.identity(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type WhisperMessage = __Infer<typeof WhisperMessage>;

export const WorldLoot = __t.object("WorldLoot", {
  lootId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  itemId: __t.string(),
});
export type WorldLoot = __Infer<typeof WorldLoot>;

export const YardVendor = __t.object("YardVendor", {
  vendorId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  label: __t.string(),
});
export type YardVendor = __Infer<typeof YardVendor>;

